#Temporal_Working
#Data Directories
data_settings:
  #emiss_dir: /home/vaithisa/Input_data/UniAugsburg_2018_Sub2020_Inlandsprinzip_Greta1.1.4.gdb
  emiss_dir: /home/vaithisa/Input_data/GRETA_2022.gdb
  urbanAtlas_dir: /home/vaithisa/Input_data/UrbanAtlas_Augsburg/UrbanAtlas_Augsburg.gdb  #/home/vaithisa/Input_data/UrbanAtlas_Germany/UrbanAtlas_Germany.gdb  #
  popul_dir: /home/vaithisa/Input_data/GHS_POP_E2020_GLOBE_R2023A_54009_100_V1_0_R4_C19/GHS_POP_E2020_GLOBE_R2023A_54009_100_V1_0_R4_C19.tif
  edgar_dir: /home/vaithisa/Input_data/EDGAR
  pm_speciation_file: /home/vaithisa/Input_data/PM_Speciation_CAMS_REG/CAMS-REG-v6_PM_split.xlsx
  building_shp: /home/vaithisa/Input_data/OB_SCH_buildingheight/OB_SCH_buildingheight.shp
  viirs_nightlight: /home/vaithisa/Input_data/VNL_npp_2024_europe.tif

# Simulation parameters
job_settings:
  job_path: /mnt/t/PhD_data/Downscale_Augsburg_full_100m #/mnt/t/PhD_data/Downscale_Augsburg_full_100m #Small_area_Emissions_Yearly  #/mnt/c/Users/vaithisa/PHD_Augsburg/Downscale_Winter_Bigarea
  job_name: test
  #min_lon: 642600 #Augsburg_random small area
  #max_lon: 643170 
  #min_lat: 5357800 
  #max_lat: 5358400 
  #min_lon: 638000 #636000 #Augsburg_center_domain
  #max_lon: 644000 #646000
  #min_lat: 5356000 #5350000
  #max_lat: 5362000 #5365000
  min_lon: 634000  #Augsburg_full_domain
  max_lon: 649000
  min_lat: 5345000
  max_lat: 5373000
  resol: 100
  epsg_code: 25832
  #species: [pm10]
  species: [n2o, nmvoc, so2, co, pm10, pm2_5, nh3, pb, cd, hg, as, ni, bc, co2, ch4, nox]
  country: Germany
  inventory: GRETA
  temporal:
    apply_temporal: true
    start_date: "2025-02-03"
    end_date: "2025-02-03"
    country: "DEU"    # Will automatically include country code 22
    profile_year: 2017
  pm_speciation:
    country_code: "DEU"
    year: 2018
