#Temporal_Working
#Data Directories
data_settings:
  emiss_dir: /home/vaithisa/Input_data/UniAugsburg_2018_Sub2020_Inlandsprinzip_Greta1.1.4.gdb
  urbanAtlas_dir: /home/vaithisa/Input_data/LU_Urban_Atlas/Landuse_Urban_Atlas_LargerArea/UrbanAtlasBBox.gdb
  #urbanAtlas_dir: /home/vaithisa/Input_data/Schwaben_LU.gdb
  popul_dir: /home/vaithisa/Input_data/GHS_POP_E2020_GLOBE_R2023A_54009_100_V1_0_R4_C19/GHS_POP_E2020_GLOBE_R2023A_54009_100_V1_0_R4_C19.tif
  edgar_dir: /home/vaithisa/Input_data/EDGAR
  pm_speciation_file: /home/vaithisa/Input_data/PM_Speciation_CAMS_REG/CAMS-REG-v6_PM_split.xlsx
  building_shp: /home/vaithisa/Input_data/OB_SCH_buildingheight.shp
  viirs_nightlight: /home/vaithisa/Input_data/VNL_npp_2024_europe.tif

# Simulation parameters
job_settings:
  job_path: /home/vaithisa/Downscale_Emissions/Downscale_Summer     #Small_area_Emissions_Yearly  #/mnt/c/Users/vaithisa/PHD_Augsburg/6months
  job_name: test
  min_lon: 639800
  max_lon: 640800
  min_lat: 5358200
  max_lat: 5359200
  #min_lon: 634000  #Augsburg_full_doamin
  #max_lon: 649000
  #min_lat: 5345000
  #max_lat: 5373000
  #min_lon: 545406.926  #Schwaben_full_doamin
  #max_lon: 739206.181  
  #min_lat: 5237452.65  
  #max_lat: 5431174.49
  resol: 10
  epsg_code: 25832
  #species: [pm10, pm2_5]
  species: [n2o, nmvoc, so2, co, pm10, pm2_5, nh3, pb, cd, hg, as, ni, bc, co2, ch4, nox]
  country: Germany
  inventory: GRETA
  temporal:
    apply_temporal: true
    start_date: "2025-05-03"
    end_date: "2025-05-03"
    country: "DEU"    # Will automatically include country code 22
    profile_year: 2017   
  pm_speciation:
    country_code: "DEU"
    year: 2018
